/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/announcements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAnnouncement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reference data for the schedule editor (semesters, slots, schedulable rooms, teachers, courses, groups) */
        get: operations["getAdminCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lesson templates (the weekly timetable) of a semester, optionally of one room */
        get: operations["listLessons"];
        put?: never;
        /** Add a weekly lesson; the board of every open screen updates over SSE */
        post: operations["createLesson"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/lessons/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteLesson"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createOverride"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/overrides/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteOverride"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/buildings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listBuildings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/buildings/{code}/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot at a moment (server now by default) — used for SSR and time-travel */
        get: operations["getBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/buildings/{code}/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Floors and rooms with geometry (cached, ETag) */
        get: operations["getBuildingMap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/buildings/{code}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All sessions of a day (time-travel bar, room panel) */
        get: operations["getTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-Sent Events stream. Events: `snapshot` (Snapshot), `announcement` (Announcement), `heartbeat` ({at}).
         *     A full `snapshot` is sent on connect and after every transition or override.
         */
        get: operations["events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{code}/day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGroupDay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/{code}/day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRoomDay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unified search over teachers / groups / rooms / courses (5 per kind) */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teachers/{id}/day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTeacherDay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/time": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server "now" and clock mode */
        get: operations["getTime"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe (DB reachable, snapshot built) */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminCatalog: {
            building: string;
            courses: components["schemas"]["CatalogCourse"][];
            /**
             * Format: uuid
             * @description The semester containing today (or the closest one)
             */
            currentSemesterId: string;
            groups: components["schemas"]["CatalogGroup"][];
            /** @description Schedulable rooms only */
            rooms: components["schemas"]["CatalogRoom"][];
            semesters: components["schemas"]["CatalogSemester"][];
            slots: components["schemas"]["CatalogSlot"][];
            teachers: components["schemas"]["TeacherRef"][];
        };
        Announcement: {
            /** Format: date-time */
            endsAt: string;
            /** Format: uuid */
            id: string;
            severity: components["schemas"]["Severity"];
            /** Format: date-time */
            startsAt: string;
            text: string;
        };
        AnnouncementRequest: {
            /** @description Show for N minutes from now (default 30) */
            durationMinutes?: number;
            severity?: components["schemas"]["Severity"];
            text: string;
        };
        BBox: {
            h: number;
            w: number;
            x: number;
            y: number;
        };
        Building: {
            /** @example A */
            code: string;
            floors: number;
            name: string;
            timezone: string;
        };
        BuildingMap: {
            building: string;
            floors: components["schemas"]["MapFloor"][];
            name: string;
            timezone: string;
            viewBox: number[];
        };
        CatalogCourse: {
            code: string;
            department?: string | null;
            title: string;
        };
        CatalogGroup: {
            code: string;
            courseYear?: number | null;
            program?: string | null;
        };
        CatalogRoom: {
            capacity?: number | null;
            code: string;
            floor: number;
            name: string;
        };
        CatalogSemester: {
            /** Format: date */
            endsOn: string;
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: date */
            startsOn: string;
        };
        CatalogSlot: {
            /**
             * @description Local time HH:MM
             * @example 10:50
             */
            endsAt: string;
            idx: number;
            /**
             * @description Local time HH:MM
             * @example 10:00
             */
            startsAt: string;
        };
        /** @enum {string} */
        ClockMode: "real" | "fixed" | "offset";
        DaySchedule: {
            /** Format: date-time */
            at: string;
            /** Format: date */
            date: string;
            sessions: components["schemas"]["SessionView"][];
            subject: {
                id: string;
                /** @enum {string} */
                kind: "room" | "teacher" | "group";
                label: string;
            };
        };
        DayTimeline: {
            /** Format: date-time */
            at: string;
            building: string;
            /** Format: date */
            date: string;
            sessions: components["schemas"]["SessionView"][];
            slots: components["schemas"]["TimeSlot"][];
        };
        Error: {
            error: {
                /** @example not_found */
                code: string;
                message: string;
            };
        };
        Health: {
            checks?: {
                [key: string]: string;
            };
            /** @enum {string} */
            status: "ok" | "degraded" | "down";
        };
        Heartbeat: {
            /** Format: date-time */
            at: string;
        };
        Lesson: {
            courseCode: string;
            courseTitle: string;
            /** @description Local time HH:MM */
            endsAt: string;
            floor: number;
            groups: string[];
            /** Format: uuid */
            id: string;
            parity: components["schemas"]["WeekParity"];
            roomCode: string;
            roomName: string;
            /** Format: uuid */
            semesterId: string;
            slotIdx: number;
            /** @description Local time HH:MM */
            startsAt: string;
            teacher: components["schemas"]["TeacherRef"];
            type: components["schemas"]["LessonType"];
            /** @description 1 = Monday */
            weekday: number;
        };
        LessonRequest: {
            courseCode: string;
            groups?: string[];
            parity?: components["schemas"]["WeekParity"];
            roomCode: string;
            /**
             * Format: uuid
             * @description Defaults to the semester containing today
             */
            semesterId?: string | null;
            slotIdx: number;
            /** Format: uuid */
            teacherId: string;
            type?: components["schemas"]["LessonType"];
            /** @description 1 = Monday */
            weekday: number;
        };
        /** @enum {string} */
        LessonType: "lecture" | "practice" | "lab";
        MapFloor: {
            name: string;
            number: number;
            planKey: string;
            rooms: components["schemas"]["MapRoom"][];
        };
        MapRoom: {
            area: number | null;
            bbox: components["schemas"]["BBox"];
            capacity: number | null;
            /** @example 103 */
            code: string;
            floor: number;
            /** @description Stable id shared with vector-map.json */
            id: string;
            label: components["schemas"]["Point"];
            /** @description Label as printed on the plan */
            mapLabel: string;
            mapType: string;
            name: string;
            /** @description SVG path in the building viewBox */
            path: string;
            schedulable: boolean;
            type: components["schemas"]["RoomType"];
            wing: components["schemas"]["Wing"];
        };
        Override: {
            /** Format: date-time */
            createdAt: string;
            /** Format: date */
            date: string;
            delayMinutes?: number | null;
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["OverrideKind"];
            /** Format: uuid */
            lessonId: string | null;
            newRoomCode?: string | null;
            /** Format: uuid */
            newTeacherId?: string | null;
            note?: string | null;
        };
        /** @enum {string} */
        OverrideKind: "cancel" | "move" | "delay" | "reassign_teacher" | "extra";
        OverrideRequest: {
            /** @description extra */
            courseCode?: string | null;
            /** Format: date */
            date: string;
            /** @description delay */
            delayMinutes?: number | null;
            /** @description extra */
            groups?: string[] | null;
            kind: components["schemas"]["OverrideKind"];
            /**
             * Format: uuid
             * @description Required for every kind except extra
             */
            lessonId?: string | null;
            /** @description move */
            newRoomCode?: string | null;
            /**
             * Format: uuid
             * @description reassign_teacher
             */
            newTeacherId?: string | null;
            note?: string | null;
            /** @description extra */
            roomCode?: string | null;
            /** @description extra */
            slotIdx?: number | null;
            /**
             * Format: uuid
             * @description extra
             */
            teacherId?: string | null;
        };
        /** @enum {string} */
        Parity: "odd" | "even";
        /**
         * @description Phase of a session relative to `at`
         * @enum {string}
         */
        Phase: "upcoming" | "soon" | "live" | "ending" | "done" | "cancelled";
        Point: {
            x: number;
            y: number;
        };
        RoomLiveState: {
            conflict: boolean;
            current: components["schemas"]["SessionView"] | null;
            floor: number;
            /** Format: date-time */
            freeUntil: string | null;
            next: components["schemas"]["SessionView"] | null;
            phase: components["schemas"]["RoomPhase"];
            roomCode: string;
            roomId: string;
            roomName: string;
        };
        /**
         * @description Phase of a room = phase of the owning session (live/ending > soon > free)
         * @enum {string}
         */
        RoomPhase: "free" | "soon" | "live" | "ending";
        /** @enum {string} */
        RoomType: "lecture" | "seminar" | "lab" | "coworking" | "admin" | "service" | "void";
        SearchCourse: {
            code: string;
            department?: string | null;
            title: string;
        };
        SearchGroup: {
            code: string;
            courseYear?: number | null;
            program?: string | null;
        };
        SearchResult: {
            courses: components["schemas"]["SearchCourse"][];
            groups: components["schemas"]["SearchGroup"][];
            q: string;
            rooms: components["schemas"]["SearchRoom"][];
            teachers: components["schemas"]["SearchTeacher"][];
        };
        SearchRoom: {
            code: string;
            floor: number;
            name: string;
            type: components["schemas"]["RoomType"];
        };
        SearchTeacher: {
            department?: string | null;
            fullName: string;
            /** Format: uuid */
            id: string;
            shortName: string;
        };
        /**
         * @description Result of applying overrides to a lesson template
         * @enum {string}
         */
        SessionStatus: "scheduled" | "cancelled" | "moved" | "delayed" | "extra";
        SessionView: {
            conflict: boolean;
            /** @example CS201 */
            courseCode: string;
            /** @example Базы данных */
            courseTitle: string;
            delayMinutes?: number | null;
            /** Format: date-time */
            endAt: string;
            floor: number;
            groups: string[];
            /** Format: uuid */
            lessonId: string | null;
            lessonType: components["schemas"]["LessonType"];
            /** @description Original room code when status=moved */
            movedFrom?: string | null;
            note?: string | null;
            phase: components["schemas"]["Phase"];
            roomCode: string;
            roomName: string;
            /** @description "{lessonId}:{date}" or "x:{overrideId}" for extra sessions */
            sessionId: string;
            /** Format: date-time */
            startAt: string;
            status: components["schemas"]["SessionStatus"];
            teacher: components["schemas"]["TeacherRef"];
        };
        /** @enum {string} */
        Severity: "info" | "warning" | "alert";
        Snapshot: {
            announcements: components["schemas"]["Announcement"][];
            /** Format: date-time */
            at: string;
            building: string;
            /**
             * Format: date
             * @description Local date the timeline was materialised for
             */
            date: string;
            /** @description Sessions in phase soon|upcoming starting within the NEXT horizon (+ cancelled/moved in the window), sorted by startAt */
            next: components["schemas"]["SessionView"][];
            /** Format: date-time */
            nextTransitionAt: string | null;
            /** @description Sessions in phase live|ending, sorted by endAt */
            now: components["schemas"]["SessionView"][];
            rooms: components["schemas"]["RoomLiveState"][];
            stats: components["schemas"]["SnapshotStats"];
        };
        SnapshotStats: {
            roomsBusy: number;
            roomsTotal: number;
            sessionsDone: number;
            sessionsToday: number;
        };
        TeacherRef: {
            department?: string | null;
            fullName: string;
            /** Format: uuid */
            id: string;
            /** @example Ахметов Д.Б. */
            shortName: string;
        };
        TimeInfo: {
            /** Format: date */
            localDate: string;
            mode: components["schemas"]["ClockMode"];
            /** Format: date-time */
            now: string;
            parity: components["schemas"]["Parity"];
            /** @example Asia/Almaty */
            timezone: string;
            /** @description Week number within the semester (1-based); 0 outside the semester */
            weekNumber: number;
        };
        TimeSlot: {
            /** Format: date-time */
            endsAt: string;
            idx: number;
            /** Format: date-time */
            startsAt: string;
        };
        /**
         * @description Which weeks a lesson template applies to
         * @enum {string}
         */
        WeekParity: "all" | "odd" | "even";
        /** @enum {string} */
        Wing: "west" | "east" | "core";
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or wrong API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        BuildingCode: string;
        /** @description Local date (YYYY-MM-DD). Defaults to today in the building timezone. */
        Date: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createAnnouncement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnnouncementRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Announcement"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getAdminCatalog: {
        parameters: {
            query?: {
                building?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCatalog"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listLessons: {
        parameters: {
            query?: {
                building?: string;
                roomCode?: string;
                /** @description Defaults to the semester containing today */
                semesterId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createLesson: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description The room, teacher or a group is already busy in that slot */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createOverride: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverrideRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Override"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteOverride: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listBuildings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Buildings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Building"][];
                };
            };
        };
    };
    getBoard: {
        parameters: {
            query?: {
                /** @description Instant to compute the snapshot for. Defaults to the server clock. */
                at?: string;
                /** @description Local date (YYYY-MM-DD) of the timeline to materialise. Defaults to the local date of `at`. */
                date?: string;
            };
            header?: never;
            path: {
                code: components["parameters"]["BuildingCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Snapshot */
            200: {
                headers: {
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getBuildingMap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["BuildingCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Map */
            200: {
                headers: {
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildingMap"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    getTimeline: {
        parameters: {
            query?: {
                /** @description Local date (YYYY-MM-DD). Defaults to today in the building timezone. */
                date?: components["parameters"]["Date"];
            };
            header?: never;
            path: {
                code: components["parameters"]["BuildingCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Day timeline */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayTimeline"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    events: {
        parameters: {
            query: {
                building: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getGroupDay: {
        parameters: {
            query?: {
                /** @description Local date (YYYY-MM-DD). Defaults to today in the building timezone. */
                date?: components["parameters"]["Date"];
            };
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions of the group for the day */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaySchedule"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getRoomDay: {
        parameters: {
            query?: {
                /** @description Local date (YYYY-MM-DD). Defaults to today in the building timezone. */
                date?: components["parameters"]["Date"];
            };
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions of the room for the day */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaySchedule"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    search: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getTeacherDay: {
        parameters: {
            query?: {
                /** @description Local date (YYYY-MM-DD). Defaults to today in the building timezone. */
                date?: components["parameters"]["Date"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions of the teacher for the day */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaySchedule"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getTime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server time */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeInfo"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
type FlattenedDeepRequired<T> = {
    [K in keyof T]-?: FlattenedDeepRequired<T[K] extends unknown[] | undefined | null ? Extract<T[K], unknown[]>[number] : T[K]>;
};
type ReadonlyArray<T> = [
    Exclude<T, undefined>
] extends [
    unknown[]
] ? Readonly<Exclude<T, undefined>> : Readonly<Exclude<T, undefined>[]>;
export const clockModeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ClockMode"]> = ["real", "fixed", "offset"];
export const dayScheduleSubjectKindValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["DaySchedule"]["subject"]["kind"]> = ["room", "teacher", "group"];
export const healthStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Health"]["status"]> = ["ok", "degraded", "down"];
export const lessonTypeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["LessonType"]> = ["lecture", "practice", "lab"];
export const overrideKindValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["OverrideKind"]> = ["cancel", "move", "delay", "reassign_teacher", "extra"];
export const parityValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Parity"]> = ["odd", "even"];
export const phaseValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Phase"]> = ["upcoming", "soon", "live", "ending", "done", "cancelled"];
export const roomPhaseValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["RoomPhase"]> = ["free", "soon", "live", "ending"];
export const roomTypeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["RoomType"]> = ["lecture", "seminar", "lab", "coworking", "admin", "service", "void"];
export const sessionStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["SessionStatus"]> = ["scheduled", "cancelled", "moved", "delayed", "extra"];
export const severityValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Severity"]> = ["info", "warning", "alert"];
export const weekParityValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["WeekParity"]> = ["all", "odd", "even"];
export const wingValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Wing"]> = ["west", "east", "core"];
