// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteLesson = `-- name: DeleteLesson :execrows
delete from lessons where id = $1
`

func (q *Queries) DeleteLesson(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLesson, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOverride = `-- name: DeleteOverride :execrows
delete from session_overrides where id = $1
`

func (q *Queries) DeleteOverride(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOverride, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBuildingByCode = `-- name: GetBuildingByCode :one
select id, code, name, timezone from buildings where code = $1
`

func (q *Queries) GetBuildingByCode(ctx context.Context, code string) (Building, error) {
	row := q.db.QueryRow(ctx, getBuildingByCode, code)
	var i Building
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Timezone,
	)
	return i, err
}

const getCourseByCode = `-- name: GetCourseByCode :one
select id, code, title, department from courses where code = $1
`

func (q *Queries) GetCourseByCode(ctx context.Context, code string) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseByCode, code)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Department,
	)
	return i, err
}

const getGroupByCode = `-- name: GetGroupByCode :one
select id, code, program, course_year from student_groups where code = $1
`

func (q *Queries) GetGroupByCode(ctx context.Context, code string) (StudentGroup, error) {
	row := q.db.QueryRow(ctx, getGroupByCode, code)
	var i StudentGroup
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Program,
		&i.CourseYear,
	)
	return i, err
}

const getLesson = `-- name: GetLesson :one
select l.id, l.semester_id, l.course_id, l.teacher_id, l.room_id, l.slot_id, l.weekday, l.parity, l.type,
       coalesce(array_agg(lg.group_id) filter (where lg.group_id is not null), '{}')::uuid[] as group_ids
from lessons l
left join lesson_groups lg on lg.lesson_id = l.id
where l.id = $1
group by l.id
`

type GetLessonRow struct {
	ID         string
	SemesterID string
	CourseID   string
	TeacherID  string
	RoomID     string
	SlotID     string
	Weekday    int16
	Parity     WeekParity
	Type       LessonType
	GroupIds   []string
}

func (q *Queries) GetLesson(ctx context.Context, id string) (GetLessonRow, error) {
	row := q.db.QueryRow(ctx, getLesson, id)
	var i GetLessonRow
	err := row.Scan(
		&i.ID,
		&i.SemesterID,
		&i.CourseID,
		&i.TeacherID,
		&i.RoomID,
		&i.SlotID,
		&i.Weekday,
		&i.Parity,
		&i.Type,
		&i.GroupIds,
	)
	return i, err
}

const getOverride = `-- name: GetOverride :one
select id, lesson_id, date, kind, new_room_id, new_teacher_id, delay_minutes, course_id, slot_id, room_id, teacher_id, group_ids, note, created_at
from session_overrides where id = $1
`

func (q *Queries) GetOverride(ctx context.Context, id string) (SessionOverride, error) {
	row := q.db.QueryRow(ctx, getOverride, id)
	var i SessionOverride
	err := row.Scan(
		&i.ID,
		&i.LessonID,
		&i.Date,
		&i.Kind,
		&i.NewRoomID,
		&i.NewTeacherID,
		&i.DelayMinutes,
		&i.CourseID,
		&i.SlotID,
		&i.RoomID,
		&i.TeacherID,
		&i.GroupIds,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getRoomByCode = `-- name: GetRoomByCode :one
select r.id, r.floor_id, f.number as floor, r.map_id, r.code, r.name, r.map_label, r.type, r.map_type, r.wing,
       r.schedulable, r.capacity, r.area, r.geometry, f.building_id
from rooms r join floors f on f.id = r.floor_id
where r.code = $1
`

type GetRoomByCodeRow struct {
	ID          string
	FloorID     string
	Floor       int32
	MapID       string
	Code        string
	Name        string
	MapLabel    string
	Type        RoomType
	MapType     string
	Wing        Wing
	Schedulable bool
	Capacity    *int32
	Area        *float64
	Geometry    []byte
	BuildingID  string
}

func (q *Queries) GetRoomByCode(ctx context.Context, code string) (GetRoomByCodeRow, error) {
	row := q.db.QueryRow(ctx, getRoomByCode, code)
	var i GetRoomByCodeRow
	err := row.Scan(
		&i.ID,
		&i.FloorID,
		&i.Floor,
		&i.MapID,
		&i.Code,
		&i.Name,
		&i.MapLabel,
		&i.Type,
		&i.MapType,
		&i.Wing,
		&i.Schedulable,
		&i.Capacity,
		&i.Area,
		&i.Geometry,
		&i.BuildingID,
	)
	return i, err
}

const getTeacher = `-- name: GetTeacher :one
select id, full_name, short_name, department, avatar_url from teachers where id = $1
`

func (q *Queries) GetTeacher(ctx context.Context, id string) (Teacher, error) {
	row := q.db.QueryRow(ctx, getTeacher, id)
	var i Teacher
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.ShortName,
		&i.Department,
		&i.AvatarUrl,
	)
	return i, err
}

const insertAnnouncement = `-- name: InsertAnnouncement :one
insert into announcements (building_id, text, severity, starts_at, ends_at)
values ($1, $2, $3, $4, $5)
returning id, building_id, text, severity, starts_at, ends_at
`

type InsertAnnouncementParams struct {
	BuildingID string
	Text       string
	Severity   string
	StartsAt   pgtype.Timestamptz
	EndsAt     pgtype.Timestamptz
}

func (q *Queries) InsertAnnouncement(ctx context.Context, arg InsertAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, insertAnnouncement,
		arg.BuildingID,
		arg.Text,
		arg.Severity,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.BuildingID,
		&i.Text,
		&i.Severity,
		&i.StartsAt,
		&i.EndsAt,
	)
	return i, err
}

const insertOverride = `-- name: InsertOverride :one
insert into session_overrides (lesson_id, date, kind, new_room_id, new_teacher_id, delay_minutes, course_id, slot_id, room_id, teacher_id, group_ids, note)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
returning id, lesson_id, date, kind, new_room_id, new_teacher_id, delay_minutes, course_id, slot_id, room_id, teacher_id, group_ids, note, created_at
`

type InsertOverrideParams struct {
	LessonID     *string
	Date         pgtype.Date
	Kind         OverrideKind
	NewRoomID    *string
	NewTeacherID *string
	DelayMinutes *int32
	CourseID     *string
	SlotID       *string
	RoomID       *string
	TeacherID    *string
	GroupIds     []string
	Note         *string
}

func (q *Queries) InsertOverride(ctx context.Context, arg InsertOverrideParams) (SessionOverride, error) {
	row := q.db.QueryRow(ctx, insertOverride,
		arg.LessonID,
		arg.Date,
		arg.Kind,
		arg.NewRoomID,
		arg.NewTeacherID,
		arg.DelayMinutes,
		arg.CourseID,
		arg.SlotID,
		arg.RoomID,
		arg.TeacherID,
		arg.GroupIds,
		arg.Note,
	)
	var i SessionOverride
	err := row.Scan(
		&i.ID,
		&i.LessonID,
		&i.Date,
		&i.Kind,
		&i.NewRoomID,
		&i.NewTeacherID,
		&i.DelayMinutes,
		&i.CourseID,
		&i.SlotID,
		&i.RoomID,
		&i.TeacherID,
		&i.GroupIds,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveAnnouncements = `-- name: ListActiveAnnouncements :many
select id, building_id, text, severity, starts_at, ends_at
from announcements
where building_id = $1 and starts_at <= $2 and ends_at > $2
order by starts_at
`

type ListActiveAnnouncementsParams struct {
	BuildingID string
	StartsAt   pgtype.Timestamptz
}

func (q *Queries) ListActiveAnnouncements(ctx context.Context, arg ListActiveAnnouncementsParams) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listActiveAnnouncements, arg.BuildingID, arg.StartsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Announcement
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.BuildingID,
			&i.Text,
			&i.Severity,
			&i.StartsAt,
			&i.EndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuildings = `-- name: ListBuildings :many
select b.id, b.code, b.name, b.timezone, (select count(*) from floors f where f.building_id = b.id)::int as floors
from buildings b order by b.code
`

type ListBuildingsRow struct {
	ID       string
	Code     string
	Name     string
	Timezone string
	Floors   int32
}

func (q *Queries) ListBuildings(ctx context.Context) ([]ListBuildingsRow, error) {
	rows, err := q.db.Query(ctx, listBuildings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBuildingsRow
	for rows.Next() {
		var i ListBuildingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Timezone,
			&i.Floors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourses = `-- name: ListCourses :many
select id, code, title, department from courses order by code
`

func (q *Queries) ListCourses(ctx context.Context) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Department,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFloors = `-- name: ListFloors :many
select id, building_id, number, plan_key, name from floors where building_id = $1 order by number
`

func (q *Queries) ListFloors(ctx context.Context, buildingID string) ([]Floor, error) {
	rows, err := q.db.Query(ctx, listFloors, buildingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Floor
	for rows.Next() {
		var i Floor
		if err := rows.Scan(
			&i.ID,
			&i.BuildingID,
			&i.Number,
			&i.PlanKey,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
select id, code, program, course_year from student_groups order by code
`

func (q *Queries) ListGroups(ctx context.Context) ([]StudentGroup, error) {
	rows, err := q.db.Query(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StudentGroup
	for rows.Next() {
		var i StudentGroup
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Program,
			&i.CourseYear,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonsBySemester = `-- name: ListLessonsBySemester :many
select l.id, l.semester_id, l.course_id, l.teacher_id, l.room_id, l.slot_id, l.weekday, l.parity, l.type,
       coalesce(array_agg(lg.group_id) filter (where lg.group_id is not null), '{}')::uuid[] as group_ids
from lessons l
left join lesson_groups lg on lg.lesson_id = l.id
where l.semester_id = $1
group by l.id
order by l.weekday, l.slot_id, l.id
`

type ListLessonsBySemesterRow struct {
	ID         string
	SemesterID string
	CourseID   string
	TeacherID  string
	RoomID     string
	SlotID     string
	Weekday    int16
	Parity     WeekParity
	Type       LessonType
	GroupIds   []string
}

func (q *Queries) ListLessonsBySemester(ctx context.Context, semesterID string) ([]ListLessonsBySemesterRow, error) {
	rows, err := q.db.Query(ctx, listLessonsBySemester, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLessonsBySemesterRow
	for rows.Next() {
		var i ListLessonsBySemesterRow
		if err := rows.Scan(
			&i.ID,
			&i.SemesterID,
			&i.CourseID,
			&i.TeacherID,
			&i.RoomID,
			&i.SlotID,
			&i.Weekday,
			&i.Parity,
			&i.Type,
			&i.GroupIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverridesBetween = `-- name: ListOverridesBetween :many
select id, lesson_id, date, kind, new_room_id, new_teacher_id, delay_minutes, course_id, slot_id, room_id, teacher_id, group_ids, note, created_at
from session_overrides where date between $1 and $2 order by date, created_at
`

type ListOverridesBetweenParams struct {
	Date   pgtype.Date
	Date_2 pgtype.Date
}

func (q *Queries) ListOverridesBetween(ctx context.Context, arg ListOverridesBetweenParams) ([]SessionOverride, error) {
	rows, err := q.db.Query(ctx, listOverridesBetween, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionOverride
	for rows.Next() {
		var i SessionOverride
		if err := rows.Scan(
			&i.ID,
			&i.LessonID,
			&i.Date,
			&i.Kind,
			&i.NewRoomID,
			&i.NewTeacherID,
			&i.DelayMinutes,
			&i.CourseID,
			&i.SlotID,
			&i.RoomID,
			&i.TeacherID,
			&i.GroupIds,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverridesByDate = `-- name: ListOverridesByDate :many
select id, lesson_id, date, kind, new_room_id, new_teacher_id, delay_minutes, course_id, slot_id, room_id, teacher_id, group_ids, note, created_at
from session_overrides where date = $1 order by created_at
`

func (q *Queries) ListOverridesByDate(ctx context.Context, date pgtype.Date) ([]SessionOverride, error) {
	rows, err := q.db.Query(ctx, listOverridesByDate, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionOverride
	for rows.Next() {
		var i SessionOverride
		if err := rows.Scan(
			&i.ID,
			&i.LessonID,
			&i.Date,
			&i.Kind,
			&i.NewRoomID,
			&i.NewTeacherID,
			&i.DelayMinutes,
			&i.CourseID,
			&i.SlotID,
			&i.RoomID,
			&i.TeacherID,
			&i.GroupIds,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomsByBuilding = `-- name: ListRoomsByBuilding :many
select r.id, r.floor_id, f.number as floor, r.map_id, r.code, r.name, r.map_label, r.type, r.map_type, r.wing,
       r.schedulable, r.capacity, r.area, r.geometry
from rooms r join floors f on f.id = r.floor_id
where f.building_id = $1
order by f.number, r.code
`

type ListRoomsByBuildingRow struct {
	ID          string
	FloorID     string
	Floor       int32
	MapID       string
	Code        string
	Name        string
	MapLabel    string
	Type        RoomType
	MapType     string
	Wing        Wing
	Schedulable bool
	Capacity    *int32
	Area        *float64
	Geometry    []byte
}

func (q *Queries) ListRoomsByBuilding(ctx context.Context, buildingID string) ([]ListRoomsByBuildingRow, error) {
	rows, err := q.db.Query(ctx, listRoomsByBuilding, buildingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomsByBuildingRow
	for rows.Next() {
		var i ListRoomsByBuildingRow
		if err := rows.Scan(
			&i.ID,
			&i.FloorID,
			&i.Floor,
			&i.MapID,
			&i.Code,
			&i.Name,
			&i.MapLabel,
			&i.Type,
			&i.MapType,
			&i.Wing,
			&i.Schedulable,
			&i.Capacity,
			&i.Area,
			&i.Geometry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSemesters = `-- name: ListSemesters :many
select id, name, starts_on, ends_on, week1_parity from semesters order by starts_on
`

func (q *Queries) ListSemesters(ctx context.Context) ([]Semester, error) {
	rows, err := q.db.Query(ctx, listSemesters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Semester
	for rows.Next() {
		var i Semester
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartsOn,
			&i.EndsOn,
			&i.Week1Parity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeachers = `-- name: ListTeachers :many
select id, full_name, short_name, department, avatar_url from teachers order by short_name
`

func (q *Queries) ListTeachers(ctx context.Context) ([]Teacher, error) {
	rows, err := q.db.Query(ctx, listTeachers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Teacher
	for rows.Next() {
		var i Teacher
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.ShortName,
			&i.Department,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimeSlots = `-- name: ListTimeSlots :many
select id, building_id, idx, starts_at, ends_at from time_slots where building_id = $1 order by idx
`

func (q *Queries) ListTimeSlots(ctx context.Context, buildingID string) ([]TimeSlot, error) {
	rows, err := q.db.Query(ctx, listTimeSlots, buildingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeSlot
	for rows.Next() {
		var i TimeSlot
		if err := rows.Scan(
			&i.ID,
			&i.BuildingID,
			&i.Idx,
			&i.StartsAt,
			&i.EndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCourses = `-- name: SearchCourses :many
select id, code, title, department from courses
where code ilike '%' || $1::text || '%' or title ilike '%' || $1::text || '%'
order by code limit 5
`

func (q *Queries) SearchCourses(ctx context.Context, q_ string) ([]Course, error) {
	rows, err := q.db.Query(ctx, searchCourses, q_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Department,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchGroups = `-- name: SearchGroups :many
select id, code, program, course_year from student_groups
where code ilike '%' || $1::text || '%' or coalesce(program, '') ilike '%' || $1::text || '%'
order by code limit 5
`

func (q *Queries) SearchGroups(ctx context.Context, q_ string) ([]StudentGroup, error) {
	rows, err := q.db.Query(ctx, searchGroups, q_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StudentGroup
	for rows.Next() {
		var i StudentGroup
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Program,
			&i.CourseYear,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRooms = `-- name: SearchRooms :many
select r.id, r.code, r.name, f.number as floor, r.type from rooms r join floors f on f.id = r.floor_id
where r.code ilike '%' || $1::text || '%' or r.name ilike '%' || $1::text || '%'
order by r.schedulable desc, r.code limit 5
`

type SearchRoomsRow struct {
	ID    string
	Code  string
	Name  string
	Floor int32
	Type  RoomType
}

func (q *Queries) SearchRooms(ctx context.Context, q_ string) ([]SearchRoomsRow, error) {
	rows, err := q.db.Query(ctx, searchRooms, q_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchRoomsRow
	for rows.Next() {
		var i SearchRoomsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Floor,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTeachers = `-- name: SearchTeachers :many
select id, full_name, short_name, department from teachers
where full_name ilike '%' || $1::text || '%' or short_name ilike '%' || $1::text || '%'
order by short_name limit 5
`

type SearchTeachersRow struct {
	ID         string
	FullName   string
	ShortName  string
	Department *string
}

func (q *Queries) SearchTeachers(ctx context.Context, q_ string) ([]SearchTeachersRow, error) {
	rows, err := q.db.Query(ctx, searchTeachers, q_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTeachersRow
	for rows.Next() {
		var i SearchTeachersRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.ShortName,
			&i.Department,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
