// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type LessonType string

const (
	LessonTypeLecture  LessonType = "lecture"
	LessonTypePractice LessonType = "practice"
	LessonTypeLab      LessonType = "lab"
)

func (e *LessonType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LessonType(s)
	case string:
		*e = LessonType(s)
	default:
		return fmt.Errorf("unsupported scan type for LessonType: %T", src)
	}
	return nil
}

type NullLessonType struct {
	LessonType LessonType
	Valid      bool // Valid is true if LessonType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLessonType) Scan(value interface{}) error {
	if value == nil {
		ns.LessonType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LessonType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLessonType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LessonType), nil
}

func (e LessonType) Valid() bool {
	switch e {
	case LessonTypeLecture,
		LessonTypePractice,
		LessonTypeLab:
		return true
	}
	return false
}

func AllLessonTypeValues() []LessonType {
	return []LessonType{
		LessonTypeLecture,
		LessonTypePractice,
		LessonTypeLab,
	}
}

type OverrideKind string

const (
	OverrideKindCancel          OverrideKind = "cancel"
	OverrideKindMove            OverrideKind = "move"
	OverrideKindDelay           OverrideKind = "delay"
	OverrideKindReassignTeacher OverrideKind = "reassign_teacher"
	OverrideKindExtra           OverrideKind = "extra"
)

func (e *OverrideKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OverrideKind(s)
	case string:
		*e = OverrideKind(s)
	default:
		return fmt.Errorf("unsupported scan type for OverrideKind: %T", src)
	}
	return nil
}

type NullOverrideKind struct {
	OverrideKind OverrideKind
	Valid        bool // Valid is true if OverrideKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOverrideKind) Scan(value interface{}) error {
	if value == nil {
		ns.OverrideKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OverrideKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOverrideKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OverrideKind), nil
}

func (e OverrideKind) Valid() bool {
	switch e {
	case OverrideKindCancel,
		OverrideKindMove,
		OverrideKindDelay,
		OverrideKindReassignTeacher,
		OverrideKindExtra:
		return true
	}
	return false
}

func AllOverrideKindValues() []OverrideKind {
	return []OverrideKind{
		OverrideKindCancel,
		OverrideKindMove,
		OverrideKindDelay,
		OverrideKindReassignTeacher,
		OverrideKindExtra,
	}
}

type RoomType string

const (
	RoomTypeLecture   RoomType = "lecture"
	RoomTypeSeminar   RoomType = "seminar"
	RoomTypeLab       RoomType = "lab"
	RoomTypeCoworking RoomType = "coworking"
	RoomTypeAdmin     RoomType = "admin"
	RoomTypeService   RoomType = "service"
	RoomTypeVoid      RoomType = "void"
)

func (e *RoomType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoomType(s)
	case string:
		*e = RoomType(s)
	default:
		return fmt.Errorf("unsupported scan type for RoomType: %T", src)
	}
	return nil
}

type NullRoomType struct {
	RoomType RoomType
	Valid    bool // Valid is true if RoomType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoomType) Scan(value interface{}) error {
	if value == nil {
		ns.RoomType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoomType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoomType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoomType), nil
}

func (e RoomType) Valid() bool {
	switch e {
	case RoomTypeLecture,
		RoomTypeSeminar,
		RoomTypeLab,
		RoomTypeCoworking,
		RoomTypeAdmin,
		RoomTypeService,
		RoomTypeVoid:
		return true
	}
	return false
}

func AllRoomTypeValues() []RoomType {
	return []RoomType{
		RoomTypeLecture,
		RoomTypeSeminar,
		RoomTypeLab,
		RoomTypeCoworking,
		RoomTypeAdmin,
		RoomTypeService,
		RoomTypeVoid,
	}
}

type WeekParity string

const (
	WeekParityAll  WeekParity = "all"
	WeekParityOdd  WeekParity = "odd"
	WeekParityEven WeekParity = "even"
)

func (e *WeekParity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WeekParity(s)
	case string:
		*e = WeekParity(s)
	default:
		return fmt.Errorf("unsupported scan type for WeekParity: %T", src)
	}
	return nil
}

type NullWeekParity struct {
	WeekParity WeekParity
	Valid      bool // Valid is true if WeekParity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWeekParity) Scan(value interface{}) error {
	if value == nil {
		ns.WeekParity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WeekParity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWeekParity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WeekParity), nil
}

func (e WeekParity) Valid() bool {
	switch e {
	case WeekParityAll,
		WeekParityOdd,
		WeekParityEven:
		return true
	}
	return false
}

func AllWeekParityValues() []WeekParity {
	return []WeekParity{
		WeekParityAll,
		WeekParityOdd,
		WeekParityEven,
	}
}

type Wing string

const (
	WingWest Wing = "west"
	WingEast Wing = "east"
	WingCore Wing = "core"
)

func (e *Wing) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Wing(s)
	case string:
		*e = Wing(s)
	default:
		return fmt.Errorf("unsupported scan type for Wing: %T", src)
	}
	return nil
}

type NullWing struct {
	Wing  Wing
	Valid bool // Valid is true if Wing is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWing) Scan(value interface{}) error {
	if value == nil {
		ns.Wing, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Wing.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWing) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Wing), nil
}

func (e Wing) Valid() bool {
	switch e {
	case WingWest,
		WingEast,
		WingCore:
		return true
	}
	return false
}

func AllWingValues() []Wing {
	return []Wing{
		WingWest,
		WingEast,
		WingCore,
	}
}

type Announcement struct {
	ID         string
	BuildingID string
	Text       string
	Severity   string
	StartsAt   pgtype.Timestamptz
	EndsAt     pgtype.Timestamptz
}

type Building struct {
	ID       string
	Code     string
	Name     string
	Timezone string
}

type Course struct {
	ID         string
	Code       string
	Title      string
	Department *string
}

type Floor struct {
	ID         string
	BuildingID string
	Number     int32
	PlanKey    string
	Name       string
}

type Lesson struct {
	ID         string
	SemesterID string
	CourseID   string
	TeacherID  string
	RoomID     string
	SlotID     string
	Weekday    int16
	Parity     WeekParity
	Type       LessonType
}

type LessonGroup struct {
	LessonID string
	GroupID  string
}

type Room struct {
	ID          string
	FloorID     string
	MapID       string
	Code        string
	Name        string
	MapLabel    string
	Type        RoomType
	MapType     string
	Wing        Wing
	Schedulable bool
	Capacity    *int32
	Area        *float64
	Geometry    []byte
}

type Semester struct {
	ID          string
	Name        string
	StartsOn    pgtype.Date
	EndsOn      pgtype.Date
	Week1Parity string
}

type SessionOverride struct {
	ID           string
	LessonID     *string
	Date         pgtype.Date
	Kind         OverrideKind
	NewRoomID    *string
	NewTeacherID *string
	DelayMinutes *int32
	CourseID     *string
	SlotID       *string
	RoomID       *string
	TeacherID    *string
	GroupIds     []string
	Note         *string
	CreatedAt    pgtype.Timestamptz
}

type StudentGroup struct {
	ID         string
	Code       string
	Program    *string
	CourseYear *int16
}

type Teacher struct {
	ID         string
	FullName   string
	ShortName  string
	Department *string
	AvatarUrl  *string
}

type TimeSlot struct {
	ID         string
	BuildingID string
	Idx        int16
	StartsAt   pgtype.Time
	EndsAt     pgtype.Time
}
