// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seed.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBuildings = `-- name: CountBuildings :one
select count(*) from buildings
`

func (q *Queries) CountBuildings(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBuildings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertBuilding = `-- name: InsertBuilding :one
insert into buildings (code, name, timezone) values ($1, $2, $3) returning id
`

type InsertBuildingParams struct {
	Code     string
	Name     string
	Timezone string
}

func (q *Queries) InsertBuilding(ctx context.Context, arg InsertBuildingParams) (string, error) {
	row := q.db.QueryRow(ctx, insertBuilding, arg.Code, arg.Name, arg.Timezone)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertCourse = `-- name: InsertCourse :one
insert into courses (code, title, department) values ($1, $2, $3) returning id
`

type InsertCourseParams struct {
	Code       string
	Title      string
	Department *string
}

func (q *Queries) InsertCourse(ctx context.Context, arg InsertCourseParams) (string, error) {
	row := q.db.QueryRow(ctx, insertCourse, arg.Code, arg.Title, arg.Department)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertFloor = `-- name: InsertFloor :one
insert into floors (building_id, number, plan_key, name) values ($1, $2, $3, $4) returning id
`

type InsertFloorParams struct {
	BuildingID string
	Number     int32
	PlanKey    string
	Name       string
}

func (q *Queries) InsertFloor(ctx context.Context, arg InsertFloorParams) (string, error) {
	row := q.db.QueryRow(ctx, insertFloor,
		arg.BuildingID,
		arg.Number,
		arg.PlanKey,
		arg.Name,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertGroup = `-- name: InsertGroup :one
insert into student_groups (code, program, course_year) values ($1, $2, $3) returning id
`

type InsertGroupParams struct {
	Code       string
	Program    *string
	CourseYear *int16
}

func (q *Queries) InsertGroup(ctx context.Context, arg InsertGroupParams) (string, error) {
	row := q.db.QueryRow(ctx, insertGroup, arg.Code, arg.Program, arg.CourseYear)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertLesson = `-- name: InsertLesson :one
insert into lessons (semester_id, course_id, teacher_id, room_id, slot_id, weekday, parity, type)
values ($1, $2, $3, $4, $5, $6, $7, $8) returning id
`

type InsertLessonParams struct {
	SemesterID string
	CourseID   string
	TeacherID  string
	RoomID     string
	SlotID     string
	Weekday    int16
	Parity     WeekParity
	Type       LessonType
}

func (q *Queries) InsertLesson(ctx context.Context, arg InsertLessonParams) (string, error) {
	row := q.db.QueryRow(ctx, insertLesson,
		arg.SemesterID,
		arg.CourseID,
		arg.TeacherID,
		arg.RoomID,
		arg.SlotID,
		arg.Weekday,
		arg.Parity,
		arg.Type,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertLessonGroup = `-- name: InsertLessonGroup :exec
insert into lesson_groups (lesson_id, group_id) values ($1, $2) on conflict do nothing
`

type InsertLessonGroupParams struct {
	LessonID string
	GroupID  string
}

func (q *Queries) InsertLessonGroup(ctx context.Context, arg InsertLessonGroupParams) error {
	_, err := q.db.Exec(ctx, insertLessonGroup, arg.LessonID, arg.GroupID)
	return err
}

const insertRoom = `-- name: InsertRoom :one
insert into rooms (floor_id, map_id, code, name, name_kk, name_en, map_label, type, map_type, wing, schedulable, capacity, area, geometry)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14) returning id
`

type InsertRoomParams struct {
	FloorID     string
	MapID       string
	Code        string
	Name        string
	NameKk      string
	NameEn      string
	MapLabel    string
	Type        RoomType
	MapType     string
	Wing        Wing
	Schedulable bool
	Capacity    *int32
	Area        *float64
	Geometry    []byte
}

func (q *Queries) InsertRoom(ctx context.Context, arg InsertRoomParams) (string, error) {
	row := q.db.QueryRow(ctx, insertRoom,
		arg.FloorID,
		arg.MapID,
		arg.Code,
		arg.Name,
		arg.NameKk,
		arg.NameEn,
		arg.MapLabel,
		arg.Type,
		arg.MapType,
		arg.Wing,
		arg.Schedulable,
		arg.Capacity,
		arg.Area,
		arg.Geometry,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertSemester = `-- name: InsertSemester :one
insert into semesters (name, starts_on, ends_on, week1_parity) values ($1, $2, $3, $4) returning id
`

type InsertSemesterParams struct {
	Name        string
	StartsOn    pgtype.Date
	EndsOn      pgtype.Date
	Week1Parity string
}

func (q *Queries) InsertSemester(ctx context.Context, arg InsertSemesterParams) (string, error) {
	row := q.db.QueryRow(ctx, insertSemester,
		arg.Name,
		arg.StartsOn,
		arg.EndsOn,
		arg.Week1Parity,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertTeacher = `-- name: InsertTeacher :one
insert into teachers (full_name, short_name, department) values ($1, $2, $3) returning id
`

type InsertTeacherParams struct {
	FullName   string
	ShortName  string
	Department *string
}

func (q *Queries) InsertTeacher(ctx context.Context, arg InsertTeacherParams) (string, error) {
	row := q.db.QueryRow(ctx, insertTeacher, arg.FullName, arg.ShortName, arg.Department)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertTimeSlot = `-- name: InsertTimeSlot :one
insert into time_slots (building_id, idx, starts_at, ends_at) values ($1, $2, $3, $4) returning id
`

type InsertTimeSlotParams struct {
	BuildingID string
	Idx        int16
	StartsAt   pgtype.Time
	EndsAt     pgtype.Time
}

func (q *Queries) InsertTimeSlot(ctx context.Context, arg InsertTimeSlotParams) (string, error) {
	row := q.db.QueryRow(ctx, insertTimeSlot,
		arg.BuildingID,
		arg.Idx,
		arg.StartsAt,
		arg.EndsAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const truncateAll = `-- name: TruncateAll :exec
truncate announcements, session_overrides, lesson_groups, lessons, time_slots, semesters, courses, student_groups, teachers, rooms, floors, buildings restart identity cascade
`

func (q *Queries) TruncateAll(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateAll)
	return err
}
