// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ClockMode.
const (
	Fixed  ClockMode = "fixed"
	Offset ClockMode = "offset"
	Real   ClockMode = "real"
)

// Valid indicates whether the value is a known member of the ClockMode enum.
func (e ClockMode) Valid() bool {
	switch e {
	case Fixed:
		return true
	case Offset:
		return true
	case Real:
		return true
	default:
		return false
	}
}

// Defines values for DayScheduleSubjectKind.
const (
	Group   DayScheduleSubjectKind = "group"
	Room    DayScheduleSubjectKind = "room"
	Teacher DayScheduleSubjectKind = "teacher"
)

// Valid indicates whether the value is a known member of the DayScheduleSubjectKind enum.
func (e DayScheduleSubjectKind) Valid() bool {
	switch e {
	case Group:
		return true
	case Room:
		return true
	case Teacher:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Degraded HealthStatus = "degraded"
	Down     HealthStatus = "down"
	Ok       HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Down:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for LessonType.
const (
	LessonTypeLab      LessonType = "lab"
	LessonTypeLecture  LessonType = "lecture"
	LessonTypePractice LessonType = "practice"
)

// Valid indicates whether the value is a known member of the LessonType enum.
func (e LessonType) Valid() bool {
	switch e {
	case LessonTypeLab:
		return true
	case LessonTypeLecture:
		return true
	case LessonTypePractice:
		return true
	default:
		return false
	}
}

// Defines values for OverrideKind.
const (
	OverrideKindCancel          OverrideKind = "cancel"
	OverrideKindDelay           OverrideKind = "delay"
	OverrideKindExtra           OverrideKind = "extra"
	OverrideKindMove            OverrideKind = "move"
	OverrideKindReassignTeacher OverrideKind = "reassign_teacher"
)

// Valid indicates whether the value is a known member of the OverrideKind enum.
func (e OverrideKind) Valid() bool {
	switch e {
	case OverrideKindCancel:
		return true
	case OverrideKindDelay:
		return true
	case OverrideKindExtra:
		return true
	case OverrideKindMove:
		return true
	case OverrideKindReassignTeacher:
		return true
	default:
		return false
	}
}

// Defines values for Parity.
const (
	Even Parity = "even"
	Odd  Parity = "odd"
)

// Valid indicates whether the value is a known member of the Parity enum.
func (e Parity) Valid() bool {
	switch e {
	case Even:
		return true
	case Odd:
		return true
	default:
		return false
	}
}

// Defines values for Phase.
const (
	PhaseCancelled Phase = "cancelled"
	PhaseDone      Phase = "done"
	PhaseEnding    Phase = "ending"
	PhaseLive      Phase = "live"
	PhaseSoon      Phase = "soon"
	PhaseUpcoming  Phase = "upcoming"
)

// Valid indicates whether the value is a known member of the Phase enum.
func (e Phase) Valid() bool {
	switch e {
	case PhaseCancelled:
		return true
	case PhaseDone:
		return true
	case PhaseEnding:
		return true
	case PhaseLive:
		return true
	case PhaseSoon:
		return true
	case PhaseUpcoming:
		return true
	default:
		return false
	}
}

// Defines values for RoomPhase.
const (
	RoomPhaseEnding RoomPhase = "ending"
	RoomPhaseFree   RoomPhase = "free"
	RoomPhaseLive   RoomPhase = "live"
	RoomPhaseSoon   RoomPhase = "soon"
)

// Valid indicates whether the value is a known member of the RoomPhase enum.
func (e RoomPhase) Valid() bool {
	switch e {
	case RoomPhaseEnding:
		return true
	case RoomPhaseFree:
		return true
	case RoomPhaseLive:
		return true
	case RoomPhaseSoon:
		return true
	default:
		return false
	}
}

// Defines values for RoomType.
const (
	RoomTypeAdmin     RoomType = "admin"
	RoomTypeCoworking RoomType = "coworking"
	RoomTypeLab       RoomType = "lab"
	RoomTypeLecture   RoomType = "lecture"
	RoomTypeSeminar   RoomType = "seminar"
	RoomTypeService   RoomType = "service"
	RoomTypeVoid      RoomType = "void"
)

// Valid indicates whether the value is a known member of the RoomType enum.
func (e RoomType) Valid() bool {
	switch e {
	case RoomTypeAdmin:
		return true
	case RoomTypeCoworking:
		return true
	case RoomTypeLab:
		return true
	case RoomTypeLecture:
		return true
	case RoomTypeSeminar:
		return true
	case RoomTypeService:
		return true
	case RoomTypeVoid:
		return true
	default:
		return false
	}
}

// Defines values for SessionStatus.
const (
	SessionStatusCancelled SessionStatus = "cancelled"
	SessionStatusDelayed   SessionStatus = "delayed"
	SessionStatusExtra     SessionStatus = "extra"
	SessionStatusMoved     SessionStatus = "moved"
	SessionStatusScheduled SessionStatus = "scheduled"
)

// Valid indicates whether the value is a known member of the SessionStatus enum.
func (e SessionStatus) Valid() bool {
	switch e {
	case SessionStatusCancelled:
		return true
	case SessionStatusDelayed:
		return true
	case SessionStatusExtra:
		return true
	case SessionStatusMoved:
		return true
	case SessionStatusScheduled:
		return true
	default:
		return false
	}
}

// Defines values for Severity.
const (
	Alert   Severity = "alert"
	Info    Severity = "info"
	Warning Severity = "warning"
)

// Valid indicates whether the value is a known member of the Severity enum.
func (e Severity) Valid() bool {
	switch e {
	case Alert:
		return true
	case Info:
		return true
	case Warning:
		return true
	default:
		return false
	}
}

// Defines values for Wing.
const (
	Core Wing = "core"
	East Wing = "east"
	West Wing = "west"
)

// Valid indicates whether the value is a known member of the Wing enum.
func (e Wing) Valid() bool {
	switch e {
	case Core:
		return true
	case East:
		return true
	case West:
		return true
	default:
		return false
	}
}

// Announcement defines model for Announcement.
type Announcement struct {
	EndsAt   time.Time          `json:"endsAt"`
	Id       openapi_types.UUID `json:"id"`
	Severity Severity           `json:"severity"`
	StartsAt time.Time          `json:"startsAt"`
	Text     string             `json:"text"`
}

// AnnouncementRequest defines model for AnnouncementRequest.
type AnnouncementRequest struct {
	// DurationMinutes Show for N minutes from now (default 30)
	DurationMinutes *int      `json:"durationMinutes,omitempty"`
	Severity        *Severity `json:"severity,omitempty"`
	Text            string    `json:"text"`
}

// BBox defines model for BBox.
type BBox struct {
	H float32 `json:"h"`
	W float32 `json:"w"`
	X float32 `json:"x"`
	Y float32 `json:"y"`
}

// Building defines model for Building.
type Building struct {
	// Code Example: A
	Code     string `json:"code"`
	Floors   int    `json:"floors"`
	Name     string `json:"name"`
	Timezone string `json:"timezone"`
}

// BuildingMap defines model for BuildingMap.
type BuildingMap struct {
	Building string     `json:"building"`
	Floors   []MapFloor `json:"floors"`
	Name     string     `json:"name"`
	Timezone string     `json:"timezone"`
	ViewBox  []float32  `json:"viewBox"`
}

// ClockMode defines model for ClockMode.
type ClockMode string

// DaySchedule defines model for DaySchedule.
type DaySchedule struct {
	At       time.Time          `json:"at"`
	Date     openapi_types.Date `json:"date"`
	Sessions []SessionView      `json:"sessions"`
	Subject  struct {
		Id    string                 `json:"id"`
		Kind  DayScheduleSubjectKind `json:"kind"`
		Label string                 `json:"label"`
	} `json:"subject"`
}

// DayScheduleSubjectKind defines model for DaySchedule.Subject.Kind.
type DayScheduleSubjectKind string

// DayTimeline defines model for DayTimeline.
type DayTimeline struct {
	At       time.Time          `json:"at"`
	Building string             `json:"building"`
	Date     openapi_types.Date `json:"date"`
	Sessions []SessionView      `json:"sessions"`
	Slots    []TimeSlot         `json:"slots"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		// Code Example: not_found
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// Health defines model for Health.
type Health struct {
	Checks *map[string]string `json:"checks,omitempty"`
	Status HealthStatus       `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Heartbeat defines model for Heartbeat.
type Heartbeat struct {
	At time.Time `json:"at"`
}

// LessonType defines model for LessonType.
type LessonType string

// MapFloor defines model for MapFloor.
type MapFloor struct {
	Name    string    `json:"name"`
	Number  int       `json:"number"`
	PlanKey string    `json:"planKey"`
	Rooms   []MapRoom `json:"rooms"`
}

// MapRoom defines model for MapRoom.
type MapRoom struct {
	Area     *float32 `json:"area"`
	Bbox     BBox     `json:"bbox"`
	Capacity *int     `json:"capacity"`

	// Code Example: 103
	Code  string `json:"code"`
	Floor int    `json:"floor"`

	// Id Stable id shared with vector-map.json
	Id    string `json:"id"`
	Label Point  `json:"label"`

	// MapLabel Label as printed on the plan
	MapLabel string `json:"mapLabel"`
	MapType  string `json:"mapType"`
	Name     string `json:"name"`

	// Path SVG path in the building viewBox
	Path        string   `json:"path"`
	Schedulable bool     `json:"schedulable"`
	Type        RoomType `json:"type"`
	Wing        Wing     `json:"wing"`
}

// Override defines model for Override.
type Override struct {
	CreatedAt    time.Time           `json:"createdAt"`
	Date         openapi_types.Date  `json:"date"`
	DelayMinutes *int                `json:"delayMinutes,omitempty"`
	Id           openapi_types.UUID  `json:"id"`
	Kind         OverrideKind        `json:"kind"`
	LessonId     *openapi_types.UUID `json:"lessonId"`
	NewRoomCode  *string             `json:"newRoomCode,omitempty"`
	NewTeacherId *openapi_types.UUID `json:"newTeacherId,omitempty"`
	Note         *string             `json:"note,omitempty"`
}

// OverrideKind defines model for OverrideKind.
type OverrideKind string

// OverrideRequest defines model for OverrideRequest.
type OverrideRequest struct {
	// CourseCode extra
	CourseCode *string            `json:"courseCode,omitempty"`
	Date       openapi_types.Date `json:"date"`

	// DelayMinutes delay
	DelayMinutes *int `json:"delayMinutes,omitempty"`

	// Groups extra
	Groups *[]string    `json:"groups,omitempty"`
	Kind   OverrideKind `json:"kind"`

	// LessonId Required for every kind except extra
	LessonId *openapi_types.UUID `json:"lessonId,omitempty"`

	// NewRoomCode move
	NewRoomCode *string `json:"newRoomCode,omitempty"`

	// NewTeacherId reassign_teacher
	NewTeacherId *openapi_types.UUID `json:"newTeacherId,omitempty"`
	Note         *string             `json:"note,omitempty"`

	// RoomCode extra
	RoomCode *string `json:"roomCode,omitempty"`

	// SlotIdx extra
	SlotIdx *int `json:"slotIdx,omitempty"`

	// TeacherId extra
	TeacherId *openapi_types.UUID `json:"teacherId,omitempty"`
}

// Parity defines model for Parity.
type Parity string

// Phase Phase of a session relative to `at`
type Phase string

// Point defines model for Point.
type Point struct {
	X float32 `json:"x"`
	Y float32 `json:"y"`
}

// RoomLiveState defines model for RoomLiveState.
type RoomLiveState struct {
	Conflict  bool         `json:"conflict"`
	Current   *SessionView `json:"current"`
	Floor     int          `json:"floor"`
	FreeUntil *time.Time   `json:"freeUntil"`
	Next      *SessionView `json:"next"`

	// Phase Phase of a room = phase of the owning session (live/ending > soon > free)
	Phase    RoomPhase `json:"phase"`
	RoomCode string    `json:"roomCode"`
	RoomId   string    `json:"roomId"`
	RoomName string    `json:"roomName"`
}

// RoomPhase Phase of a room = phase of the owning session (live/ending > soon > free)
type RoomPhase string

// RoomType defines model for RoomType.
type RoomType string

// SearchCourse defines model for SearchCourse.
type SearchCourse struct {
	Code       string  `json:"code"`
	Department *string `json:"department,omitempty"`
	Title      string  `json:"title"`
}

// SearchGroup defines model for SearchGroup.
type SearchGroup struct {
	Code       string  `json:"code"`
	CourseYear *int    `json:"courseYear,omitempty"`
	Program    *string `json:"program,omitempty"`
}

// SearchResult defines model for SearchResult.
type SearchResult struct {
	Courses  []SearchCourse  `json:"courses"`
	Groups   []SearchGroup   `json:"groups"`
	Q        string          `json:"q"`
	Rooms    []SearchRoom    `json:"rooms"`
	Teachers []SearchTeacher `json:"teachers"`
}

// SearchRoom defines model for SearchRoom.
type SearchRoom struct {
	Code  string   `json:"code"`
	Floor int      `json:"floor"`
	Name  string   `json:"name"`
	Type  RoomType `json:"type"`
}

// SearchTeacher defines model for SearchTeacher.
type SearchTeacher struct {
	Department *string            `json:"department,omitempty"`
	FullName   string             `json:"fullName"`
	Id         openapi_types.UUID `json:"id"`
	ShortName  string             `json:"shortName"`
}

// SessionStatus Result of applying overrides to a lesson template
type SessionStatus string

// SessionView defines model for SessionView.
type SessionView struct {
	Conflict bool `json:"conflict"`

	// CourseCode Example: CS201
	CourseCode string `json:"courseCode"`

	// CourseTitle Example: Базы данных
	CourseTitle  string              `json:"courseTitle"`
	DelayMinutes *int                `json:"delayMinutes,omitempty"`
	EndAt        time.Time           `json:"endAt"`
	Floor        int                 `json:"floor"`
	Groups       []string            `json:"groups"`
	LessonId     *openapi_types.UUID `json:"lessonId"`
	LessonType   LessonType          `json:"lessonType"`

	// MovedFrom Original room code when status=moved
	MovedFrom *string `json:"movedFrom,omitempty"`
	Note      *string `json:"note,omitempty"`

	// Phase Phase of a session relative to `at`
	Phase    Phase  `json:"phase"`
	RoomCode string `json:"roomCode"`
	RoomName string `json:"roomName"`

	// SessionId "{lessonId}:{date}" or "x:{overrideId}" for extra sessions
	SessionId string    `json:"sessionId"`
	StartAt   time.Time `json:"startAt"`

	// Status Result of applying overrides to a lesson template
	Status  SessionStatus `json:"status"`
	Teacher TeacherRef    `json:"teacher"`
}

// Severity defines model for Severity.
type Severity string

// Snapshot defines model for Snapshot.
type Snapshot struct {
	Announcements []Announcement `json:"announcements"`
	At            time.Time      `json:"at"`
	Building      string         `json:"building"`

	// Date Local date the timeline was materialised for
	Date openapi_types.Date `json:"date"`

	// Next Sessions in phase soon|upcoming starting within the NEXT horizon (+ cancelled/moved in the window), sorted by startAt
	Next             []SessionView `json:"next"`
	NextTransitionAt *time.Time    `json:"nextTransitionAt"`

	// Now Sessions in phase live|ending, sorted by endAt
	Now   []SessionView   `json:"now"`
	Rooms []RoomLiveState `json:"rooms"`
	Stats SnapshotStats   `json:"stats"`
}

// SnapshotStats defines model for SnapshotStats.
type SnapshotStats struct {
	RoomsBusy     int `json:"roomsBusy"`
	RoomsTotal    int `json:"roomsTotal"`
	SessionsDone  int `json:"sessionsDone"`
	SessionsToday int `json:"sessionsToday"`
}

// TeacherRef defines model for TeacherRef.
type TeacherRef struct {
	Department *string            `json:"department,omitempty"`
	FullName   string             `json:"fullName"`
	Id         openapi_types.UUID `json:"id"`

	// ShortName Example: Ахметов Д.Б.
	ShortName string `json:"shortName"`
}

// TimeInfo defines model for TimeInfo.
type TimeInfo struct {
	LocalDate openapi_types.Date `json:"localDate"`
	Mode      ClockMode          `json:"mode"`
	Now       time.Time          `json:"now"`
	Parity    Parity             `json:"parity"`

	// Timezone Example: Asia/Almaty
	Timezone string `json:"timezone"`

	// WeekNumber Week number within the semester (1-based); 0 outside the semester
	WeekNumber int `json:"weekNumber"`
}

// TimeSlot defines model for TimeSlot.
type TimeSlot struct {
	EndsAt   time.Time `json:"endsAt"`
	Idx      int       `json:"idx"`
	StartsAt time.Time `json:"startsAt"`
}

// Wing defines model for Wing.
type Wing string

// BuildingCode defines model for BuildingCode.
type BuildingCode = string

// Date defines model for Date.
type Date = openapi_types.Date

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// GetBoardParams defines parameters for GetBoard.
type GetBoardParams struct {
	// At Instant to compute the snapshot for. Defaults to the server clock.
	At *time.Time `form:"at,omitempty" json:"at,omitempty"`

	// Date Local date (YYYY-MM-DD) of the timeline to materialise. Defaults to the local date of `at`.
	Date *openapi_types.Date `form:"date,omitempty" json:"date,omitempty"`
}

// GetTimelineParams defines parameters for GetTimeline.
type GetTimelineParams struct {
	// Date Local date (YYYY-MM-DD). Defaults to today in the building timezone.
	Date *Date `form:"date,omitempty" json:"date,omitempty"`
}

// EventsParams defines parameters for Events.
type EventsParams struct {
	Building string `form:"building" json:"building"`
}

// GetGroupDayParams defines parameters for GetGroupDay.
type GetGroupDayParams struct {
	// Date Local date (YYYY-MM-DD). Defaults to today in the building timezone.
	Date *Date `form:"date,omitempty" json:"date,omitempty"`
}

// GetRoomDayParams defines parameters for GetRoomDay.
type GetRoomDayParams struct {
	// Date Local date (YYYY-MM-DD). Defaults to today in the building timezone.
	Date *Date `form:"date,omitempty" json:"date,omitempty"`
}

// SearchParams defines parameters for Search.
type SearchParams struct {
	Q string `form:"q" json:"q"`
}

// GetTeacherDayParams defines parameters for GetTeacherDay.
type GetTeacherDayParams struct {
	// Date Local date (YYYY-MM-DD). Defaults to today in the building timezone.
	Date *Date `form:"date,omitempty" json:"date,omitempty"`
}

// CreateAnnouncementJSONRequestBody defines body for CreateAnnouncement for application/json ContentType.
type CreateAnnouncementJSONRequestBody = AnnouncementRequest

// CreateOverrideJSONRequestBody defines body for CreateOverride for application/json ContentType.
type CreateOverrideJSONRequestBody = OverrideRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /api/v1/admin/announcements)
	CreateAnnouncement(w http.ResponseWriter, r *http.Request)

	// (POST /api/v1/admin/overrides)
	CreateOverride(w http.ResponseWriter, r *http.Request)

	// (DELETE /api/v1/admin/overrides/{id})
	DeleteOverride(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /api/v1/buildings)
	ListBuildings(w http.ResponseWriter, r *http.Request)
	// GetBoard Snapshot at a moment (server now by default) — used for SSR and time-travel
	// (GET /api/v1/buildings/{code}/board)
	GetBoard(w http.ResponseWriter, r *http.Request, code BuildingCode, params GetBoardParams)
	// GetBuildingMap Floors and rooms with geometry (cached, ETag)
	// (GET /api/v1/buildings/{code}/map)
	GetBuildingMap(w http.ResponseWriter, r *http.Request, code BuildingCode)
	// GetTimeline All sessions of a day (time-travel bar, room panel)
	// (GET /api/v1/buildings/{code}/timeline)
	GetTimeline(w http.ResponseWriter, r *http.Request, code BuildingCode, params GetTimelineParams)
	// Events Server-Sent Events stream. Events: `snapshot` (Snapshot), `announcement` (Announcement), `heartbeat` ({at}).
	// A full `snapshot` is sent on connect and after every transition or override.
	// (GET /api/v1/events)
	Events(w http.ResponseWriter, r *http.Request, params EventsParams)

	// (GET /api/v1/groups/{code}/day)
	GetGroupDay(w http.ResponseWriter, r *http.Request, code string, params GetGroupDayParams)

	// (GET /api/v1/rooms/{code}/day)
	GetRoomDay(w http.ResponseWriter, r *http.Request, code string, params GetRoomDayParams)
	// Search Unified search over teachers / groups / rooms / courses (5 per kind)
	// (GET /api/v1/search)
	Search(w http.ResponseWriter, r *http.Request, params SearchParams)

	// (GET /api/v1/teachers/{id}/day)
	GetTeacherDay(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params GetTeacherDayParams)
	// GetTime Server "now" and clock mode
	// (GET /api/v1/time)
	GetTime(w http.ResponseWriter, r *http.Request)
	// Healthz Liveness probe
	// (GET /healthz)
	Healthz(w http.ResponseWriter, r *http.Request)
	// Readyz Readiness probe (DB reachable, snapshot built)
	// (GET /readyz)
	Readyz(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (POST /api/v1/admin/announcements)
func (_ Unimplemented) CreateAnnouncement(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/admin/overrides)
func (_ Unimplemented) CreateOverride(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /api/v1/admin/overrides/{id})
func (_ Unimplemented) DeleteOverride(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/buildings)
func (_ Unimplemented) ListBuildings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetBoard Snapshot at a moment (server now by default) — used for SSR and time-travel
// (GET /api/v1/buildings/{code}/board)
func (_ Unimplemented) GetBoard(w http.ResponseWriter, r *http.Request, code BuildingCode, params GetBoardParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetBuildingMap Floors and rooms with geometry (cached, ETag)
// (GET /api/v1/buildings/{code}/map)
func (_ Unimplemented) GetBuildingMap(w http.ResponseWriter, r *http.Request, code BuildingCode) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetTimeline All sessions of a day (time-travel bar, room panel)
// (GET /api/v1/buildings/{code}/timeline)
func (_ Unimplemented) GetTimeline(w http.ResponseWriter, r *http.Request, code BuildingCode, params GetTimelineParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Events Server-Sent Events stream. Events: `snapshot` (Snapshot), `announcement` (Announcement), `heartbeat` ({at}).
// A full `snapshot` is sent on connect and after every transition or override.
// (GET /api/v1/events)
func (_ Unimplemented) Events(w http.ResponseWriter, r *http.Request, params EventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/groups/{code}/day)
func (_ Unimplemented) GetGroupDay(w http.ResponseWriter, r *http.Request, code string, params GetGroupDayParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/rooms/{code}/day)
func (_ Unimplemented) GetRoomDay(w http.ResponseWriter, r *http.Request, code string, params GetRoomDayParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Search Unified search over teachers / groups / rooms / courses (5 per kind)
// (GET /api/v1/search)
func (_ Unimplemented) Search(w http.ResponseWriter, r *http.Request, params SearchParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/teachers/{id}/day)
func (_ Unimplemented) GetTeacherDay(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params GetTeacherDayParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetTime Server "now" and clock mode
// (GET /api/v1/time)
func (_ Unimplemented) GetTime(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Healthz Liveness probe
// (GET /healthz)
func (_ Unimplemented) Healthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Readyz Readiness probe (DB reachable, snapshot built)
// (GET /readyz)
func (_ Unimplemented) Readyz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateAnnouncement operation middleware
func (siw *ServerInterfaceWrapper) CreateAnnouncement(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAnnouncement(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOverride operation middleware
func (siw *ServerInterfaceWrapper) CreateOverride(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOverride(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteOverride operation middleware
func (siw *ServerInterfaceWrapper) DeleteOverride(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteOverride(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListBuildings operation middleware
func (siw *ServerInterfaceWrapper) ListBuildings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBuildings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBoard operation middleware
func (siw *ServerInterfaceWrapper) GetBoard(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "code" -------------
	var code BuildingCode

	err = runtime.BindStyledParameterWithOptions("simple", "code", chi.URLParam(r, "code"), &code, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBoardParams

	// ------------- Optional query parameter "at" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "at", r.URL.Query(), &params.At, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "at"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "at", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "date" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "date", r.URL.Query(), &params.Date, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "date"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBoard(w, r, code, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBuildingMap operation middleware
func (siw *ServerInterfaceWrapper) GetBuildingMap(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "code" -------------
	var code BuildingCode

	err = runtime.BindStyledParameterWithOptions("simple", "code", chi.URLParam(r, "code"), &code, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBuildingMap(w, r, code)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTimeline operation middleware
func (siw *ServerInterfaceWrapper) GetTimeline(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "code" -------------
	var code BuildingCode

	err = runtime.BindStyledParameterWithOptions("simple", "code", chi.URLParam(r, "code"), &code, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTimelineParams

	// ------------- Optional query parameter "date" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "date", r.URL.Query(), &params.Date, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "date"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTimeline(w, r, code, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Events operation middleware
func (siw *ServerInterfaceWrapper) Events(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params EventsParams

	// ------------- Required query parameter "building" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "building", r.URL.Query(), &params.Building, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "building"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "building", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Events(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGroupDay operation middleware
func (siw *ServerInterfaceWrapper) GetGroupDay(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "code" -------------
	var code string

	err = runtime.BindStyledParameterWithOptions("simple", "code", chi.URLParam(r, "code"), &code, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetGroupDayParams

	// ------------- Optional query parameter "date" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "date", r.URL.Query(), &params.Date, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "date"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGroupDay(w, r, code, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRoomDay operation middleware
func (siw *ServerInterfaceWrapper) GetRoomDay(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "code" -------------
	var code string

	err = runtime.BindStyledParameterWithOptions("simple", "code", chi.URLParam(r, "code"), &code, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRoomDayParams

	// ------------- Optional query parameter "date" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "date", r.URL.Query(), &params.Date, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "date"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoomDay(w, r, code, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Search operation middleware
func (siw *ServerInterfaceWrapper) Search(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchParams

	// ------------- Required query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Search(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTeacherDay operation middleware
func (siw *ServerInterfaceWrapper) GetTeacherDay(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTeacherDayParams

	// ------------- Optional query parameter "date" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "date", r.URL.Query(), &params.Date, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "date"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTeacherDay(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTime operation middleware
func (siw *ServerInterfaceWrapper) GetTime(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTime(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Healthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Readyz operation middleware
func (siw *ServerInterfaceWrapper) Readyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Readyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.Healthz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.Readyz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/time", wrapper.GetTime)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/buildings", wrapper.ListBuildings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/buildings/{code}/map", wrapper.GetBuildingMap)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/buildings/{code}/board", wrapper.GetBoard)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/buildings/{code}/timeline", wrapper.GetTimeline)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/rooms/{code}/day", wrapper.GetRoomDay)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/teachers/{id}/day", wrapper.GetTeacherDay)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/groups/{code}/day", wrapper.GetGroupDay)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/search", wrapper.Search)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/events", wrapper.Events)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/overrides", wrapper.CreateOverride)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/admin/overrides/{id}", wrapper.DeleteOverride)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/announcements", wrapper.CreateAnnouncement)
	})

	return r
}

type BadRequestJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type CreateAnnouncementRequestObject struct {
	Body *CreateAnnouncementJSONRequestBody
}

type CreateAnnouncementResponseObject interface {
	VisitCreateAnnouncementResponse(w http.ResponseWriter) error
}

type CreateAnnouncement201JSONResponse Announcement

func (response CreateAnnouncement201JSONResponse) VisitCreateAnnouncementResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAnnouncement400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateAnnouncement400JSONResponse) VisitCreateAnnouncementResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAnnouncement401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateAnnouncement401JSONResponse) VisitCreateAnnouncementResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOverrideRequestObject struct {
	Body *CreateOverrideJSONRequestBody
}

type CreateOverrideResponseObject interface {
	VisitCreateOverrideResponse(w http.ResponseWriter) error
}

type CreateOverride201JSONResponse Override

func (response CreateOverride201JSONResponse) VisitCreateOverrideResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOverride400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateOverride400JSONResponse) VisitCreateOverrideResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOverride401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateOverride401JSONResponse) VisitCreateOverrideResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOverride404JSONResponse struct{ NotFoundJSONResponse }

func (response CreateOverride404JSONResponse) VisitCreateOverrideResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteOverrideRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteOverrideResponseObject interface {
	VisitDeleteOverrideResponse(w http.ResponseWriter) error
}

type DeleteOverride204Response struct {
}

func (response DeleteOverride204Response) VisitDeleteOverrideResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteOverride401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteOverride401JSONResponse) VisitDeleteOverrideResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteOverride404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteOverride404JSONResponse) VisitDeleteOverrideResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListBuildingsRequestObject struct {
}

type ListBuildingsResponseObject interface {
	VisitListBuildingsResponse(w http.ResponseWriter) error
}

type ListBuildings200JSONResponse []Building

func (response ListBuildings200JSONResponse) VisitListBuildingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetBoardRequestObject struct {
	Code   BuildingCode `json:"code"`
	Params GetBoardParams
}

type GetBoardResponseObject interface {
	VisitGetBoardResponse(w http.ResponseWriter) error
}

type GetBoard200ResponseHeaders struct {
	ETag *string
}

type GetBoard200JSONResponse struct {
	Body    Snapshot
	Headers GetBoard200ResponseHeaders
}

func (response GetBoard200JSONResponse) VisitGetBoardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetBoard304Response struct {
}

func (response GetBoard304Response) VisitGetBoardResponse(w http.ResponseWriter) error {
	w.WriteHeader(304)
	return nil
}

type GetBoard400JSONResponse struct{ BadRequestJSONResponse }

func (response GetBoard400JSONResponse) VisitGetBoardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetBoard404JSONResponse struct{ NotFoundJSONResponse }

func (response GetBoard404JSONResponse) VisitGetBoardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetBuildingMapRequestObject struct {
	Code BuildingCode `json:"code"`
}

type GetBuildingMapResponseObject interface {
	VisitGetBuildingMapResponse(w http.ResponseWriter) error
}

type GetBuildingMap200ResponseHeaders struct {
	ETag *string
}

type GetBuildingMap200JSONResponse struct {
	Body    BuildingMap
	Headers GetBuildingMap200ResponseHeaders
}

func (response GetBuildingMap200JSONResponse) VisitGetBuildingMapResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetBuildingMap304Response struct {
}

func (response GetBuildingMap304Response) VisitGetBuildingMapResponse(w http.ResponseWriter) error {
	w.WriteHeader(304)
	return nil
}

type GetBuildingMap404JSONResponse struct{ NotFoundJSONResponse }

func (response GetBuildingMap404JSONResponse) VisitGetBuildingMapResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetTimelineRequestObject struct {
	Code   BuildingCode `json:"code"`
	Params GetTimelineParams
}

type GetTimelineResponseObject interface {
	VisitGetTimelineResponse(w http.ResponseWriter) error
}

type GetTimeline200JSONResponse DayTimeline

func (response GetTimeline200JSONResponse) VisitGetTimelineResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTimeline400JSONResponse struct{ BadRequestJSONResponse }

func (response GetTimeline400JSONResponse) VisitGetTimelineResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetTimeline404JSONResponse struct{ NotFoundJSONResponse }

func (response GetTimeline404JSONResponse) VisitGetTimelineResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type EventsRequestObject struct {
	Params EventsParams
}

type EventsResponseObject interface {
	VisitEventsResponse(w http.ResponseWriter) error
}

type Events200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response Events200TexteventStreamResponse) VisitEventsResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		// If w doesn't support flushing, fall back to io.Copy.
		_, err := io.Copy(w, response.Body)
		return err
	}
	// text/event-stream messages are typically small; use a
	// modest buffer and flush after each chunk so clients see
	// events immediately instead of waiting on OS buffering.
	buf := make([]byte, 4096)
	for {
		n, err := response.Body.Read(buf)
		if n > 0 {
			if _, writeErr := w.Write(buf[:n]); writeErr != nil {
				return writeErr
			}
			flusher.Flush()
		}
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
	}
}

type Events404JSONResponse struct{ NotFoundJSONResponse }

func (response Events404JSONResponse) VisitEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetGroupDayRequestObject struct {
	Code   string `json:"code"`
	Params GetGroupDayParams
}

type GetGroupDayResponseObject interface {
	VisitGetGroupDayResponse(w http.ResponseWriter) error
}

type GetGroupDay200JSONResponse DaySchedule

func (response GetGroupDay200JSONResponse) VisitGetGroupDayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetGroupDay400JSONResponse struct{ BadRequestJSONResponse }

func (response GetGroupDay400JSONResponse) VisitGetGroupDayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetGroupDay404JSONResponse struct{ NotFoundJSONResponse }

func (response GetGroupDay404JSONResponse) VisitGetGroupDayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetRoomDayRequestObject struct {
	Code   string `json:"code"`
	Params GetRoomDayParams
}

type GetRoomDayResponseObject interface {
	VisitGetRoomDayResponse(w http.ResponseWriter) error
}

type GetRoomDay200JSONResponse DaySchedule

func (response GetRoomDay200JSONResponse) VisitGetRoomDayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRoomDay400JSONResponse struct{ BadRequestJSONResponse }

func (response GetRoomDay400JSONResponse) VisitGetRoomDayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetRoomDay404JSONResponse struct{ NotFoundJSONResponse }

func (response GetRoomDay404JSONResponse) VisitGetRoomDayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type SearchRequestObject struct {
	Params SearchParams
}

type SearchResponseObject interface {
	VisitSearchResponse(w http.ResponseWriter) error
}

type Search200JSONResponse SearchResult

func (response Search200JSONResponse) VisitSearchResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Search400JSONResponse struct{ BadRequestJSONResponse }

func (response Search400JSONResponse) VisitSearchResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetTeacherDayRequestObject struct {
	Id     openapi_types.UUID `json:"id"`
	Params GetTeacherDayParams
}

type GetTeacherDayResponseObject interface {
	VisitGetTeacherDayResponse(w http.ResponseWriter) error
}

type GetTeacherDay200JSONResponse DaySchedule

func (response GetTeacherDay200JSONResponse) VisitGetTeacherDayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTeacherDay400JSONResponse struct{ BadRequestJSONResponse }

func (response GetTeacherDay400JSONResponse) VisitGetTeacherDayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetTeacherDay404JSONResponse struct{ NotFoundJSONResponse }

func (response GetTeacherDay404JSONResponse) VisitGetTeacherDayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetTimeRequestObject struct {
}

type GetTimeResponseObject interface {
	VisitGetTimeResponse(w http.ResponseWriter) error
}

type GetTime200JSONResponse TimeInfo

func (response GetTime200JSONResponse) VisitGetTimeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type HealthzRequestObject struct {
}

type HealthzResponseObject interface {
	VisitHealthzResponse(w http.ResponseWriter) error
}

type Healthz200JSONResponse Health

func (response Healthz200JSONResponse) VisitHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ReadyzRequestObject struct {
}

type ReadyzResponseObject interface {
	VisitReadyzResponse(w http.ResponseWriter) error
}

type Readyz200JSONResponse Health

func (response Readyz200JSONResponse) VisitReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Readyz503JSONResponse Health

func (response Readyz503JSONResponse) VisitReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /api/v1/admin/announcements)
	CreateAnnouncement(ctx context.Context, request CreateAnnouncementRequestObject) (CreateAnnouncementResponseObject, error)

	// (POST /api/v1/admin/overrides)
	CreateOverride(ctx context.Context, request CreateOverrideRequestObject) (CreateOverrideResponseObject, error)

	// (DELETE /api/v1/admin/overrides/{id})
	DeleteOverride(ctx context.Context, request DeleteOverrideRequestObject) (DeleteOverrideResponseObject, error)

	// (GET /api/v1/buildings)
	ListBuildings(ctx context.Context, request ListBuildingsRequestObject) (ListBuildingsResponseObject, error)
	// GetBoard Snapshot at a moment (server now by default) — used for SSR and time-travel
	// (GET /api/v1/buildings/{code}/board)
	GetBoard(ctx context.Context, request GetBoardRequestObject) (GetBoardResponseObject, error)
	// GetBuildingMap Floors and rooms with geometry (cached, ETag)
	// (GET /api/v1/buildings/{code}/map)
	GetBuildingMap(ctx context.Context, request GetBuildingMapRequestObject) (GetBuildingMapResponseObject, error)
	// GetTimeline All sessions of a day (time-travel bar, room panel)
	// (GET /api/v1/buildings/{code}/timeline)
	GetTimeline(ctx context.Context, request GetTimelineRequestObject) (GetTimelineResponseObject, error)
	// Events Server-Sent Events stream. Events: `snapshot` (Snapshot), `announcement` (Announcement), `heartbeat` ({at}).
	// A full `snapshot` is sent on connect and after every transition or override.
	// (GET /api/v1/events)
	Events(ctx context.Context, request EventsRequestObject) (EventsResponseObject, error)

	// (GET /api/v1/groups/{code}/day)
	GetGroupDay(ctx context.Context, request GetGroupDayRequestObject) (GetGroupDayResponseObject, error)

	// (GET /api/v1/rooms/{code}/day)
	GetRoomDay(ctx context.Context, request GetRoomDayRequestObject) (GetRoomDayResponseObject, error)
	// Search Unified search over teachers / groups / rooms / courses (5 per kind)
	// (GET /api/v1/search)
	Search(ctx context.Context, request SearchRequestObject) (SearchResponseObject, error)

	// (GET /api/v1/teachers/{id}/day)
	GetTeacherDay(ctx context.Context, request GetTeacherDayRequestObject) (GetTeacherDayResponseObject, error)
	// GetTime Server "now" and clock mode
	// (GET /api/v1/time)
	GetTime(ctx context.Context, request GetTimeRequestObject) (GetTimeResponseObject, error)
	// Healthz Liveness probe
	// (GET /healthz)
	Healthz(ctx context.Context, request HealthzRequestObject) (HealthzResponseObject, error)
	// Readyz Readiness probe (DB reachable, snapshot built)
	// (GET /readyz)
	Readyz(ctx context.Context, request ReadyzRequestObject) (ReadyzResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateAnnouncement operation middleware
func (sh *strictHandler) CreateAnnouncement(w http.ResponseWriter, r *http.Request) {
	var request CreateAnnouncementRequestObject

	var body CreateAnnouncementJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAnnouncement(ctx, request.(CreateAnnouncementRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAnnouncement")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAnnouncementResponseObject); ok {
		if err := validResponse.VisitCreateAnnouncementResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateOverride operation middleware
func (sh *strictHandler) CreateOverride(w http.ResponseWriter, r *http.Request) {
	var request CreateOverrideRequestObject

	var body CreateOverrideJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOverride(ctx, request.(CreateOverrideRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOverride")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateOverrideResponseObject); ok {
		if err := validResponse.VisitCreateOverrideResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteOverride operation middleware
func (sh *strictHandler) DeleteOverride(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeleteOverrideRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteOverride(ctx, request.(DeleteOverrideRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteOverride")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteOverrideResponseObject); ok {
		if err := validResponse.VisitDeleteOverrideResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListBuildings operation middleware
func (sh *strictHandler) ListBuildings(w http.ResponseWriter, r *http.Request) {
	var request ListBuildingsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListBuildings(ctx, request.(ListBuildingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListBuildings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListBuildingsResponseObject); ok {
		if err := validResponse.VisitListBuildingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetBoard operation middleware
func (sh *strictHandler) GetBoard(w http.ResponseWriter, r *http.Request, code BuildingCode, params GetBoardParams) {
	var request GetBoardRequestObject

	request.Code = code
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetBoard(ctx, request.(GetBoardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBoard")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetBoardResponseObject); ok {
		if err := validResponse.VisitGetBoardResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetBuildingMap operation middleware
func (sh *strictHandler) GetBuildingMap(w http.ResponseWriter, r *http.Request, code BuildingCode) {
	var request GetBuildingMapRequestObject

	request.Code = code

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetBuildingMap(ctx, request.(GetBuildingMapRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBuildingMap")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetBuildingMapResponseObject); ok {
		if err := validResponse.VisitGetBuildingMapResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTimeline operation middleware
func (sh *strictHandler) GetTimeline(w http.ResponseWriter, r *http.Request, code BuildingCode, params GetTimelineParams) {
	var request GetTimelineRequestObject

	request.Code = code
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTimeline(ctx, request.(GetTimelineRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTimeline")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTimelineResponseObject); ok {
		if err := validResponse.VisitGetTimelineResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Events operation middleware
func (sh *strictHandler) Events(w http.ResponseWriter, r *http.Request, params EventsParams) {
	var request EventsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Events(ctx, request.(EventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Events")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EventsResponseObject); ok {
		if err := validResponse.VisitEventsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetGroupDay operation middleware
func (sh *strictHandler) GetGroupDay(w http.ResponseWriter, r *http.Request, code string, params GetGroupDayParams) {
	var request GetGroupDayRequestObject

	request.Code = code
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGroupDay(ctx, request.(GetGroupDayRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGroupDay")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGroupDayResponseObject); ok {
		if err := validResponse.VisitGetGroupDayResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRoomDay operation middleware
func (sh *strictHandler) GetRoomDay(w http.ResponseWriter, r *http.Request, code string, params GetRoomDayParams) {
	var request GetRoomDayRequestObject

	request.Code = code
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRoomDay(ctx, request.(GetRoomDayRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRoomDay")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRoomDayResponseObject); ok {
		if err := validResponse.VisitGetRoomDayResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Search operation middleware
func (sh *strictHandler) Search(w http.ResponseWriter, r *http.Request, params SearchParams) {
	var request SearchRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Search(ctx, request.(SearchRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Search")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SearchResponseObject); ok {
		if err := validResponse.VisitSearchResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTeacherDay operation middleware
func (sh *strictHandler) GetTeacherDay(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params GetTeacherDayParams) {
	var request GetTeacherDayRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTeacherDay(ctx, request.(GetTeacherDayRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTeacherDay")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTeacherDayResponseObject); ok {
		if err := validResponse.VisitGetTeacherDayResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTime operation middleware
func (sh *strictHandler) GetTime(w http.ResponseWriter, r *http.Request) {
	var request GetTimeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTime(ctx, request.(GetTimeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTime")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTimeResponseObject); ok {
		if err := validResponse.VisitGetTimeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Healthz operation middleware
func (sh *strictHandler) Healthz(w http.ResponseWriter, r *http.Request) {
	var request HealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Healthz(ctx, request.(HealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Healthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthzResponseObject); ok {
		if err := validResponse.VisitHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Readyz operation middleware
func (sh *strictHandler) Readyz(w http.ResponseWriter, r *http.Request) {
	var request ReadyzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Readyz(ctx, request.(ReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Readyz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReadyzResponseObject); ok {
		if err := validResponse.VisitReadyzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FzLbhw3un4Vos5ZSDgldSt2DowOspAsxxFsy4ZauRiWEbOr/u5mVEWWSVZfojRwcICsspkAeZBgMIPZ",
	"TOYZ5FeYJxnwVpcuVl8syfEAs7K6qkj+d37/z5++CiKWZowClSLoXQUZ5jgFCVz/OspJEhM6eshiUL8J",
	"DXpBhuU4CAOKUwh6QaRehQGHtznhEAc9yXMIAxGNIcVqjJxn6jshOaGjYLEIg2Ms9WwxiIiTTBKmpn3K",
	"IpygGEtAOy9fvny59+zZ3vHx7j46hiHOEymQZEiyGM8RoUiOAQ0sdUiSFH5gFPaD0JD4Ngc+L2lUkwZV",
	"moaMp1iWb5ZpXCiGRMaoACMHHJ/B2xyEVL8iRiVQ/SfOsoREWLHQ+V4oPq4qy/w3h2HQC/6rU8q4Y96K",
	"ziPOGTdL1eVwhGPE7WKLMDhl8guW0/juFz5lEg31Uosw+IriXI4ZJz/AB1j6GRFCKZJxNOWMjtDhixN0",
	"CXNtLna0mvyQUpbTCFJLSsZZBlwSoyWgsTiUDf3uKfNoKjkMSFz7Ns9J7PtMwAQ4kfN13PXdd2qMxFxu",
	"RYyEmfS7S+larwJDofq0QldludAJ4XWxBBt8D5E2par0KuZcF2Kcc63aZ4Tm0j6q6ao/ZlM0ZBydotR8",
	"g4acpYiyKdqJja+ie93dIAxSPCNpnga9g/v3u2GQEmp/FsQRKmEE/H3F7ISW4tlToCM5DnqfPDArud8H",
	"4RqR6jl84jo6YrOmfMYVJdE8HRjip96nM+/TuefpEk2zQH2mpg2DsZ84G/uaBEY2VsMMp1miRh367G2Y",
	"MGaCfFMVJmxeeYzUBtr1hmq3BT1TZVyx7iqenuGsydagwvAKZoiEVKwzoWc4+0KN0CyZuTDneP6+vIfB",
	"hMDUmktBQUPxKZ6dmJf3tYmWP+pELImy4NwnTrfwSsE+TFh0+czZBVUu+CrggBM1jMxABRU2HAqoOkLJ",
	"3DGe96MxxHkCTb3gLWJcbDf+NduvigVCEEY312jfDPiawNSnVJEbWTSoN1tAY/1LYjbcQlaMpTrw4mgM",
	"PAiDEWd55hVWggeQrPcPvUJo4rkZ0lTc0hArLKxjv2WoIiqf4o/x/JykkBB6Q82t9L4/Tq0Jk5tPpiTR",
	"T5hsztTucDWZ69XWSNxAnCY08T9uxmrK5HcGhHnkl4IQeLR59HXfrzUtQ56Pny8BJ3LsoXwM0aUxozgm",
	"Chrg5EXti2YAXZ5bSCxzUfUzdqlkDiOOYx2UYjalHi9bot7O00I+lwPA8ibmv7Qc9sOFpyAEo+f6cclR",
	"ApHMuZo04ziSJALj8N7YUexLDWJbdyW7u3i38SzB9AnMveNURNtqwzxTIXCd51hqyqWLLcus55Obm7up",
	"IA46o6B5kuCB8g6TWjb21cHA7LyrONBgbhEGEc5wZFFmy8QVCTb986B7rxVN+bVgtpglDC3VuojESIwx",
	"hxhNiRyjCUSS8b0UZ/s6r1q1u6zi9QUjVBrAkT11A5aSbfUYYYEyrkiNETMptdKbN/LgzFl20wTbbFMX",
	"Cpq8f/0YqTeNLL6EMs2Nw8APo6xipQFjCWBaWuVqsSgr00wovG73slXff9OagNXBbSFlS0YpLbuOM486",
	"HxVbDI2tW0t2WrYC9PnM8wlwTmLPph5xwBLiw7tAZTEkeF7JC9f7z4YZtoNbq7ThWH5CTIEi0eH2xLtA",
	"C2EVk4WpsgZX1trk+3OD/d53QSY3WclnbBYpWqUUbIcVVa8ykSdLUDbCNNLGlbIJBFapuoCHhSAj+l0J",
	"cmEmOfZuVG7y1ipCxHIuwMm3HgDMtBsI7b0Ns76e47CsRjxYKkasN2SN90U7L8tJX3WD9s5dYNib2n6d",
	"njNrPbpAAxPgc6QWQDCLIJPIkXtTh6kvai1pay+qz+IxwLtyMwNHbmidKh04iWdbz1CxKtkujffUlD/L",
	"1H7jCxIvsKu4FQg8VgNgAtTr+C/GWHiEph8jNkQY2ewIcUiwJBNAkqE3WL7RpUmzRp5FLDUbo2Aa5yRE",
	"WxBQl3aZ4oaJVQnEflo0zGmEnhsW3XxiUqb/lEygL21EWg52dJiQSPqhSZRz7irnSfJ8GPRebZH0vl5W",
	"+WqwOeQAX1FJktbtfwMvnd0msZmzmHXQzJjWkm96Hfckbn116seiS5q2k1SWqowu0ZohPSz1WyrTiqkq",
	"8DbDWe8yamn0OcrcE4WK2ZQqTOy8aUd5SMf4B7rIu917gJTvuL8VGbsVF1O/29zL50sFNvamrgJSQjG3",
	"masSyJTxS+OqOE4J1d/wicluJ4z4HbYPmEfjhxoatNdCPLt7hrl0Rz5r7VcSmWxeIjFf+3RnqH2sC32b",
	"E2uAz0vAfDOEnHE24jjdHhtqCtrpPgORJ63AbJsKXEVnnhJcCYy2mM4I1TPb21uoVVj+veWKYsvddjqL",
	"W9YWQN4GlSUK6TgWwkL8KxTnrYW02tuKvaD9JGOrZHnlwY4LlXrKdqac+Jqnjdv59jBPktM2tjY9zh0z",
	"LjfbJ/QE5feV9f2s6ljdL6qay9BceaSO+FmWzPVxt8X1urUBIwPrkYQ0S0ym40KxrRvommgJikwOF7sk",
	"Tv/VnrNVd+ptIUwtmyuLYQ/7n3QPfDI2A85dJC5HXP9y/dv13979jK7/cv3b9e/Xv7/7+d1Pt1NrALpV",
	"1WOF43hiWlsxu4grNypHJLXS8Sq3rBSZF1b9X3ATMOrW9pyTEaE4MeBCOS2ajoEiUyv/3BnO7WVUG+G8",
	"zTFeq5dbROTLmS6CK6eGRe9KaX9xESDG0UUw6105ZzuJ1VOdHytfQcVxji9WSMzlNlZVHmlsAJptpCh3",
	"pbUnWOazMxg2z0AKsdRrRKXn1r2yZnSNk02xFhs7yTi/K1j3wGZ/sCy7PVyUI3TIgjCYYk4ttkyA+4+k",
	"+xRnYsx8xzqVJpfNd/laY5HHvW/9rLS1902Bf2nPbNEUC5RiCZzghAhT1qkWBdoKYi6HW6q8W0tHhNpk",
	"Q+UHP7p0HGmdqj+mRI5tdf700bfnSPeBqSzkf1Cx+3R0CHFF/CmhMZvuhkgwLiFGgzkqLeQ2jnoVR+cc",
	"U6HPGle45AYRbbqJaFTO9KPJmKpcOWu/DZ62w7X1IoTvNFxiuZ4k6zh9/fGKk2995G3tqyF8t1gJbJVU",
	"i6S47oNe96+R0XBiPetRLub+DVq/PmcSJ/73LqQf19t1PF+csxh7F/FUDOyKYYW65YmWlvZxXonhHx0a",
	"ruC0P7376frv13999//X/7j+M7r+df/6l/0gvFW8fE5SOFEhvyGHRIXD402r/6nFEavMvuyAKiPAZtE8",
	"w5s0JdpC6lKbWKUFTxDcOUxSrE/7GotMAS5Pi5P8emj6BuASmZJlNTALSEFI4GjnYG+ABcS7n6EuYrkU",
	"JIbaF0G4zrqN86auIlI0l5V6qJFYCKVNq7rL5hbac2ctzrtlc23DSmcbt8x+Y/dxB1GmIPQIrP+JGAd/",
	"e4qAKFci6iv7MOwfZsQ2Y+gW9THgWMvS9qh/u3eYkT3TM+Eiuxmh+6WJdZTlnBInimd0EWDCM8YlGjDM",
	"YwtwMcopmQAXRM6Lc/Z9ZHBnx+5zbEQivdsJt5k/ZgjoiFD47IJGCVGGjhhN5igGTiaAdM0KhECYxihi",
	"OZUxm1LbBuzwi5A4zfSUGLlov39Bi5JbL3iI0ywXaktDhy9OgjDQlGq+Dva7+10lf5YBxRkJesG9/e7+",
	"PXsmruXZwRnpTA46ugDZacC+jJlzSWWBuqFZZQzBQ31mWkN7xjhAyCMWz2+t1d3Xa72oW6ItkNcuGqh8",
	"+i5I8DXdG1noA8X73W7bbAV5ncolCD3kYP2Q2i2Cql/ocwXnEa9eL5QT4ZHQ7VW6oPxafV1XcVEtWafe",
	"ojviblS7fPj9gdVacPcxqFQNur9+UHGJ5dZsoHNF4oUJiAkYoFA3hWP9vGIK1ZtNr7xXmTR8ab/ItAZL",
	"KfqXlH6/GbENWfFHL263W2hORuDxtadEyKPiqwbv3a0MfqMMqLjz0KzCN29RFZSpd47Rkis/s52riMWw",
	"6OhNtJXzxyCP9AcNo/JRX37SqV2nW4TLtnFChcRUIsmQGp/baoCwu6fa0pduw2mUxyfAUaQAbtv9N9O+",
	"7L/91oqZNryf5w4si5qFZNWSRZPgpJyHDXVrwK1d23t9QyvcJHH2GVvxLrSwTq/+6ByP6vM3rhkuwuCe",
	"L0qcMolSFpMhuUEw3zpQ5GmK+bzCD8ISYZQyhSDQjrU0yqZooLCgVusu+uf//YpyW5tC/f6ZRoXKGvYk",
	"xxPTFmndzx1jrPG+1Nz/afW9yjWhm3ngXdpLlUrfjUdN/F1Zy/urXvefG2SvyxymM3kELAXJ52gnwkqH",
	"IVLk7gbbR1ZZuY7SpuDiysqN4+ua73Vqe6dWUL2A47GCYzwvAucf4OeHSVIcf5hWlBjP0U7FedEA89Cc",
	"IWWYQrK71pth4jIwr3ofmdd+OLYU/yvVyM2vl6/XpoSZNGTuCcnBNF+scLtGtO8/QnbgTeOsjqh7fRVe",
	"jWDsxPv2Zw+9cbv/G7TjwvJuiN5U8903aKea66nXY3fv5Q3aucJysbt/QQ/RME+S6oxEIKHWZhRFjFKI",
	"pHZ8PJTgukdlUfZFjBcH1jaRt4bAbRWibgjmIMn5vS2ztrm87gg51hXU9Th9+/9y4OOIBMUlSp9RVdxQ",
	"oSQtPb2lql+xqfB/kPCw2r31prChUs8YS/+j01KnOox+fCoVukWnVZGmg2eziP12pQort/T/9/66S/p3",
	"iuWrLXIexZk34r30UwvwX1ENypARsQ6fyLWHoY5xcvWHgVodZNvD0M6nKAOuW/drO65RRU17bjpdEFnn",
	"kfbwaVOnvGFB5N/QRa00P0Iv1RvsGtAc3KEgi9M6rxR1ZqhJ9CEcdBFQNr0IzIFBwqJL5A6bHM9zISG1",
	"HI/1neMfWrn90r6/Q27ttWcPr8+fLLH4lEyAghAo42zQyhMHHM/bWTozr/8QjvTaymQ/7d77AMupbJWb",
	"JWtyVGSQUpBo5/hIfReN8SCBsKyCqaxA7nrlvDBt6C6i5TwJesFYyqzX6eiy05gJ2XvQfdANKuXPq+V8",
	"Q+jc0T4svLH6zMThypMCAleemapqdZghdPF68a8AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
